services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: collections-platform
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    env_file:
      - ./server/.env
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb_collection
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_collection
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge